### PR TITLE
Detect AVX2

### LINKED ISSUE #4: Detect AVX2
Detect AVX2 support within setup.py and enable it when compiling.

### PR DESCRIPTION
**Pull request by alimanfoo**
This PR modifies setup.py to detect support for AVX2 via the [cpuinfo](https://github.com/workhorsy/py-cpuinfo) module.

Resolves #4.

cc @FrancescAlted this looks like it works, maybe useful for bcolz and python-blosc too.

### CODE REVIEW

**Comment by FrancescAlted** [comment]
Cool.  Although provided that you [cannot currently pass a better optimization level larger than -O1 in Python extensions](https://github.com/Blosc/python-blosc/issues/110), I am -0 in porting this back to bcolz or python-blosc.  I think it is much better that people start using the C-Blosc library directly as stated in:

https://github.com/Blosc/python-blosc#compiling-with-an-installed-blosc-library-recommended

**Comment by alimanfoo** [comment]
Fair enough. It is strange but I am not seeing any segfaults with zarr, so
I have not limited the compiler optimisation level in setup.py. I haven't
used heavily yet tho so the same issue may still be there.

On Thursday, 14 April 2016, FrancescAlted <notifications@github.com> wrote:

> Cool. Although provided that you cannot currently pass a better
> optimization level larger than -O1 in Python extensions
> <https://github.com/Blosc/python-blosc/issues/110>, I am -0 in porting
> this back to bcolz or python-blosc. I think it is much better that people
> start using the C-Blosc library directly as stated in:
>
>
> https://github.com/Blosc/python-blosc#compiling-with-an-installed-blosc-library-recommended
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/alimanfoo/zarr/pull/20#issuecomment-209907133>
>


-- 
Alistair Miles
Head of Epidemiological Informatics
Centre for Genomics and Global Health <http://cggh.org>
The Wellcome Trust Centre for Human Genetics
Roosevelt Drive
Oxford
OX3 7BN
United Kingdom
Email: alimanfoo@googlemail.com <alimanfoo@gmail.com>
Web: http://purl.org/net/aliman
Twitter: https://twitter.com/alimanfoo
Tel: +44 (0)1865 287721

**Comment by FrancescAlted** [comment]
No more segfaults?  Hmmm, strange... I think they will come again, but I think it is nice that you enable -O2 or higher in zarr just to keep track of this.

**Comment by alimanfoo** [comment]
FWIW I have never seen segfaults with zarr, only bcolz. The previous
version of zarr only used the blosc contextual functions. The next zarr
release which I'm just preparing will have the option to use either the
contextual functions or the non-contextual functions like bcolz, so
something may come up. I'll try to run some heavier tests and see what
happens.

On Thursday, 14 April 2016, FrancescAlted <notifications@github.com> wrote:

> No more segfaults? Hmmm, strange... I think they will come again, but I
> think it is nice that you enable -O2 or higher in zarr just to keep track
> of this.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/alimanfoo/zarr/pull/20#issuecomment-210088188>
>


-- 
Alistair Miles
Head of Epidemiological Informatics
Centre for Genomics and Global Health <http://cggh.org>
The Wellcome Trust Centre for Human Genetics
Roosevelt Drive
Oxford
OX3 7BN
United Kingdom
Email: alimanfoo@googlemail.com <alimanfoo@gmail.com>
Web: http://purl.org/net/aliman
Twitter: https://twitter.com/alimanfoo
Tel: +44 (0)1865 287721

**Pull request merged**
