### PR TITLE
Add a `digest` method for Zarr Arrays

### PR DESCRIPTION
**Pull request by jakirkham**
Follow-up to PR ( https://github.com/alimanfoo/zarr/pull/203 ).

This implements an equivalent method to `hashlib`'s `digest` method for Zarr Arrays. Makes sure to document it as well.

### CODE REVIEW

**Comment by jakirkham** [comment]
Thoughts on this @alimanfoo?

**Comment by alimanfoo** [comment]
Looks fine to me.

**Comment by alimanfoo** [comment]
Good to go?

**Comment by alimanfoo** [comment]
Thanks.

**Comment by jakirkham** [comment]
Thank you. :)

**Pull request merged**
